In [1]:
import xarray as xr
import numpy as np

In [70]:
dimensions=['x','y','z']
locs=['player1','player2','player3']
time=range(0,10,1)
data=np.random.rand(10,3)

xyzData=np.random.rand(1,10,3)
print xyzData


[[[0.91944277 0.28622292 0.70819325]
  [0.44631785 0.08462234 0.18218319]
  [0.68226187 0.37874034 0.75978435]
  [0.36171985 0.02826219 0.13096996]
  [0.00880531 0.39459592 0.16417269]
  [0.43484713 0.74787534 0.50851518]
  [0.12062203 0.98961357 0.18686917]
  [0.3767821  0.80303219 0.55100834]
  [0.59663779 0.34376496 0.93793914]
  [0.54228491 0.77733238 0.83114257]]]


In [76]:
ds=xr.Dataset({'player1':(['x','y','z'],xyzData)},
             coords={'position':['x','y','z'],
                     'time':time})
ds

<xarray.Dataset>
Dimensions:   (position: 3, time: 10, x: 1, y: 10, z: 3)
Coordinates:
  * position  (position) |S1 'x' 'y' 'z'
  * time      (time) int64 0 1 2 3 4 5 6 7 8 9
Dimensions without coordinates: x, y, z
Data variables:
    player1   (x, y, z) float64 0.9194 0.2862 0.7082 0.4463 0.08462 0.1822 ...